### ISSUE TITLE
unknown log level: warn

### ISSUE THREAD

**Issue by seriousManual** [alexgorbatchev/winston-logentries#1]
the logentries backend only accepts the keywords 'warning' and 'err' as log levels whereas winston assignes 'warn' and 'error'.
these logentries are dropped, not something one would expect...

**Comment by LukasBombach** [comment]
Hey there, the situation has changed and right now this package is broken. Logentries.com changed its levels from "warning" and "err" to "warn" and "error". I'll open a PR to fix this.

**Comment by LukasBombach** [comment]
There you go https://github.com/alexgorbatchev/winston-logentries/pull/9
