### ISSUE TITLE
Cant log multiple levels, only the one defined in { level: '' }

### ISSUE THREAD

**Issue by horacio-giovine** [alexgorbatchev/winston-logentries#10]
I defined the transport like in the example code like this:
`var logger = new (winston.Logger)({

```
transports: [

  new (winston.transports.Console)({ level: 'silly' }),

  new (winston.transports.Logentries)({

    token: '24d46ebb-c28b-4a5d-8279-abfa19bfd546',

    level: 'silly',

   levels: { error: 0, warn: 1, info: 2, verbose: 3, debug: 4, silly: 5 }
  })

]
```

  })`

Then i print some test logs:

```
logger.silly('Logentries logger init succesful')

  logger.debug('Logentries logger init succesful')

  logger.verbose('Logentries logger init succesful')

  logger.info('Logentries logger init succesful')

  logger.warn('Logentries logger init succesful')

  logger.error('Logentries logger init succesful')
```

They all show in the console, but only one of them gets sent to logentries, the one specified in the level attribute.

I know i have to set the minimum level, but no matter if i set silly or error i only get one log, the one that was set.

Any idea what it could be? Am i doing something wrong?
Any help is greatly appreciated!

**Comment by hvo408-brightplan** [comment]
+1

**Comment by horacio-giovine** [comment]
One way i can think of solving this is to create multiple transports with different logging levels each, but i cant set the name for the transport created, maybe a fix there could be made to allow the user to set the transport name?

**Comment by alexgorbatchev** [comment]
Hm... I added a test for this case and I can tell that a call to logentries is being placed... Would you be able to make a failing test for me? (btw, i just converted this module to ES6)

**Comment by horacio-giovine** [comment]
im sorry i am not yet familiar with testing, but this code is the one im using:

`
import winston from 'winston'
import Logentries from 'winston-logentries'

export function basicLogger () {
  var logger = new (winston.Logger)({
    transports: [
      new (winston.transports.Console)({ level: 'silly' }),
      new (winston.transports.Logentries)({
        token: '24d46ebb-c28b-4a5d-8279-abfa19bfd546',
        level: 'silly',
        levels: { error: 0, warn: 1, info: 2, verbose: 3, debug: 4, silly: 5 }
      })
    ]
  })

  logger.silly('Logentries logger init succesful')
  logger.debug('Logentries logger init succesful')
  logger.verbose('Logentries logger init succesful')
  logger.info('Logentries logger init succesful')
  logger.warn('Logentries logger init succesful')
  logger.error('Logentries logger init succesful')

  return logger
}

`

that should print only the 'silly' log in your logentries account, if i can help in any way please contact me

**Comment by alexgorbatchev** [comment]
Is it possible that your app is exiting before it has a chance to flush the logs?

**Comment by horacio-giovine** [comment]
i dont think so, i passed the logger to an endpoint i use and i can call it repeatedly, and i always get the same result. Where you able to reproduce it with the code i sent? do you want me to send you anything in special?

**Comment by DominikPalo** [comment]
I have same problem - only messages with level defined in options are passed to Logentries. App is not short-runnig - it's a HAPI server (example code is on top of the main file).

**Code:** (minimum level explicitly set to `warn`)
```
import logger = require("winston");
require("winston-logentries");
logger.add(logger.transports["Logentries"], {token: my_le_token, level: "warn"});

logger.info("Test message");
logger.warn("Test message");
logger.error("Test message");
```

**Console output:**
> error: Test message
> info: Test message
> warn: Test message

**Logentries output:** (the error message is missing)
> 5 Oct 2016 18:26:40.588 2016-10-05T16:26:38.858Z warn Test message


or


**Code:** (level is not explicitly set => default level `info`)
```
import logger = require("winston");
require("winston-logentries");
logger.add(logger.transports["Logentries"], {token: my_le_token});

logger.info("Test message");
logger.warn("Test message");
logger.error("Test message");
```

**Console output:**
> error: Test message
> info: Test message
> warn: Test message

**Logentries output:** (the warn and error messages are missing)
> 5 Oct 2016 18:26:40.588 2016-10-05T16:27:31.221Z info Test message

**Comment by krzkaczor** [comment]
Just use https://github.com/rapid7/le_node it has built in winston support but currently it's broken for newest winston. Temp fix on my fork https://github.com/krzkaczor/le_node 

It's ridiculous that even official package doesn't work. I am gonna migrate away from logentries asap.

**Comment by alexgorbatchev** [comment]
I'm deprecating this module since I no longer have any context on this and nobody seems to be willing to take over it.

**Comment by krzkaczor** [comment]
@alexgorbatchev Very good decision :) Don't get me wrong - you did great work but there is just too many modules that do similar things but none of them does everything correctly. Much appreciated.
