### ISSUE TITLE
Unknow log level: err

### ISSUE THREAD

**Issue by beinnova** [alexgorbatchev/winston-logentries#8]
Hi,
I use your module for log on logentries from my application. My application use Express and, for log errors, I use [express-winston](https://github.com/bithavoc/express-winston).
When application log at `info` level, I can see teh log on logentries. The problem is when the application try to log on `erro` and `warning` level becous your module report errors:
`unknow level err` when ofcoars level is `error`. And same but `warning` instand of `err` when level is `warning`.
Can you help me pleas?

Thanks.

**Comment by alexgorbatchev** [comment]
Closed by #9
